In [1]:
import cv2, numpy as np
import time
from matplotlib import pyplot as plt
%matplotlib inline

def imshow(tit, image) :
    plt.title(tit)    
    if len(image.shape) == 3 :
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    else :
        plt.imshow(image, cmap="gray")
    plt.show()

In [2]:
frame = cv2.imread("./mart2.jpg")
roi = frame.copy()
gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

gray_blur = cv2.medianBlur(gray, 9)

thr, mask = cv2.threshold(gray, 0, 255,
        cv2.THRESH_BINARY+cv2.THRESH_OTSU)

#침식후 팽창
opened = cv2.morphologyEx(mask,cv2.MORPH_OPEN,cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
    
                          ,iterations =10) 


cont_img = opened.copy()
contours, _ = cv2.findContours(cont_img, cv2.RETR_EXTERNAL,
                              cv2.CHAIN_APPROX_SIMPLE)


In [6]:
cnt = contours[0]
peri = cv2.arcLength(cnt,True)
approx = cv2.approxPolyDP(cnt,0.02* peri, True)
frame_copy = frame.copy()
arr = []
for a in approx:
    arr.append(list(a[0]))
    print(a[0])


[2097  558]
[619 603]
[ 506 3920]
[2349 3887]


In [7]:
pts1= [[0,0],[0,0],[0,0],[0,0]]
arr=sorted(arr, key=lambda arr: [arr[0],arr[1]]) 
pts1[0]=arr[0]
pts1[2] = arr[1]
pts1[1] = arr[2]
pts1[3] = arr[3]
pts1 =np.float32(pts1)
pts1

array([[ 506., 3920.],
       [2097.,  558.],
       [ 619.,  603.],
       [2349., 3887.]], dtype=float32)

In [8]:
height, width = frame.shape[:2]
print(height, width)

4032 3024


In [13]:
pts2 =np.float32([[0,0], [width,0], [0,height],[width,height]])
M = cv2.getPerspectiveTransform(pts1,pts2)
print(M)

[[-1.13001767e+00 -3.84962304e-02  7.22694162e+02]
 [-1.51863930e+00 -7.18666008e-01  3.58560224e+03]
 [-7.44049327e-04  1.53058995e-05  1.00000000e+00]]


In [14]:
img_result = cv2.warpPerspective(frame,M,(width,height))
cv2.imwrite("result_out2.jpg",img_result)

True

In [15]:
gray=cv2.imread("result_out2.jpg",cv2.IMREAD_GRAYSCALE)
print(gray.shape)
gray = cv2.medianBlur(gray, 5)
out = cv2.adaptiveThreshold(gray,255,
                            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                            cv2.THRESH_BINARY,21,2)
#imshow('binary',out)
cv2.imwrite('result_print.jpg',out)

(4032, 3024)


True

In [12]:
import pytesseract
#tesseract exe 파일을 실행시키겠다
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract'

#저장후 불러오기
print(pytesseract.image_to_string('mart_result.jpg', lang ='kor'))

4  못데쇼핑(주) 못데마르 침성점
102-05-29300       강의테
롯데마트 호암로 1    1『나069-715-2500
영수증 미지참시 교흰/환불 불가(30일내)
교흰/환불 구매짐에서만기능 능(걸제카드지잠)
: 체크키드. 취소시 대금흰급은 최대7일 소요
[등록] 2019-08-23 12:09 005: _0074-0008

이020000나에에이에에애우우에우아 고기0-==ㅁㅠㅁㅋㅁㅋ~ㅠㄷㄷㄷ = 이르

 

상품명   ! 단 가수량 금액
쉐프리 그노스레이크 10,900 1 _ 10,900
과세 물품 |액          9,909
부 {가 세         991
합 ，계           10,900
결제금액           10,900
0001 비씨은련체크(80) 1452 51795151
청구액(일시) 메 16         10900
『「
프     로워
고 학이구
꼬  느니
5월 25일(토), 롯데워터파크

아외 전면 가창:

> 롯데마트 영수증 할인권 제시 시
롯데워터피크-종일군 권 할인

- 성수기(6.3"7,.12) , 29,90(원

- 극성수기(7,1378.25) ; 39,900원
[> 잠깐! 개쿠폰맵 회원 추가 혜택

. - 엠 제시시 당일 찜질방 50% 할인

※ 본인 및 동반 1인까지 할인

※ 롯데워터파크 고객센터 1661-2000

※ 지세한샤항 매장내 고지물 참고

때!

(

비비비비삐!

74000
롯
